#!/bin/bash
## ----------------------------------------------
## @File: bullet

bullet_pos_x=$(($current_pos_x+1))
bullet_pos_y=$(($ROWS-2))

is_bullet=1


##
## @name: reset_bullet()
## @desc: place the bullet back to the center
function reset_bullet() {
    bullet_pos_x=$(($current_pos_x+1))
    bullet_pos_y=$(($ROWS-2))
}

##
## @name: shoot()
## @desc: checks if there is a bullet
function shoot() {
    is_bullet=0
}

##
## @name: draw_bullet()
## @desc: draws the bullet on the screen
function draw_bullet() {
    if [ $is_bullet -eq 0 ]; then
        set_position $bullet_pos_y $bullet_pos_x
        echo -ne " "
        set_position $(($bullet_pos_y-1)) $bullet_pos_x
        echo -ne "|"
        if [ $bullet_pos_y == 2 ]; then
            is_bullet=1
            set_position $(($bullet_pos_y-1)) $bullet_pos_x
            echo -ne " "
            reset_bullet
        fi
        cursor_home
        ((bullet_pos_y-=1))
    fi

}

## END: bullet
